### ISSUE TITLE
It does not work on WP

### ISSUE THREAD

**Issue by Ambiens** [nir9/itemslide#43]
It works only in one direction.
Tested in Lumia 532, WP8.1

**Comment by nir9** [comment]
Thanks for the report, i'll test it on wp8.

**Comment by maartenmachiels** [comment]
Hi, is this issue fixed already? Any view on when it would be fixed?

**Comment by nir9** [comment]
See issue #53

**Comment by nir9** [comment]
Windows Phone is not supported, closing issue.
