### ISSUE TITLE
Wrong calculation with different item size

### ISSUE THREAD

**Issue by simeonwong** [nir9/itemslide#49]
When the first item with small width, slide will display strange

HTML:

```
<div class="itemSlider">
    <ul>
        <li style="width:299px;height:500px;background:#000;"></li>
        <li style="width:599px;height:500px;background:#F00;"></li>
        <li style="width:499px;height:500px;background:#0F0;"></li>
        <li style="width:699px;height:500px;background:#00F;"></li>
    </ul>
</div>
```

JS:
`
itemSlider.itemslide({
disable_clicktoslide:true,
left_sided:true,
disable_scroll:true
});
`
result :
![1455616185397](https://cloud.githubusercontent.com/assets/8513125/13072745/e95426f0-d4d5-11e5-9b19-a1712de9176a.jpg)

**Comment by nir9** [comment]
Interesting, this bug indeed looks to occur when slides have different sizes, looking into this, thanks for reporting

**Comment by nir9** [comment]
Thanks for reporting, was an interesting bug, the code was indeed assuming that all slides had the same width, but now it handles different widths correctly :)
