### ISSUE TITLE
if "left_sided: true" the "click to slide" doesn't work

### ISSUE THREAD

**Issue by cgahmann** [nir9/itemslide#63]
I've tested with "left_sided: true" and the "click to slide" doesn't work.

My code:

``` javascript
<script src="jquery-3.0.0.min.js"></script>
<script src="itemslide.min.js"></script>
<script src="jquery.mousewheel.min.js"></script>
<script>
var carousel;

$(document).ready(function () {
    carousel = $(".images");

    carousel.itemslide({
        left_sided: true
    }); //initialize itemslide

    $(window).resize(function () {
        carousel.reload();
    }); //Recalculate width and center positions and sizes when window is resized
});
</script>
```

Width default "left_sided: false" everything is fine.

**Comment by octojoerg** [comment]
Additionally I have to say: if you show control buttons (like here http://itemslide.github.io/examples/buttons_carousel/), `left_sided` is activated and lets say 4 items are visible, control buttons trigger first after 4 clicks.

**Comment by PurHur** [comment]
The original bug here is fixed. This is a new one octojoerg

**Comment by nir9** [comment]
Looks like this scenario works fine currently, so closing

@octojoerg I don't exactly understand the scenario but as @PurHur has pointed out it seems unrelated to this bug, so if still relevant welcome to open a new issue
