### ISSUE TITLE
Problem when using more than one itemslide per page

### ISSUE THREAD

**Issue by eldegwy** [nir9/itemslide#78]
i'm not able to set different options for different itemslides per the same page

i found the reason in dist/itemslide.js line 367
Was 
         carousel.create($.extend(defaults, options), this);
updated to
         carousel.create($.extend({},defaults, options), this);

Please make this fix :D Thank for your great itemslide

**Comment by bjornbak** [comment]
I stumbled upon the same problem and @eldegwy 's fix does solve it! Please add to master.

**Comment by pamplo** [comment]
The line in dist/itemslide.js moved to 364.

The solution worked for me and there is already a pull request with this change in place: #79

**Comment by nir9** [comment]
Related to #86 , fixed therefore closing this one as well.
