### ISSUE TITLE
After using addSlide, the swipe is not working properly

### ISSUE THREAD

**Issue by rekhakum** [nir9/itemslide#82]
Hi, I am using addSlide() events to attach new files dynamically. But after files, the swipe is not working smoothly.  Especially the scenario is like swipe little left but swipes right. Actually, it got struck.

**Comment by nir9** [comment]
I tried and addSlide works fine and the new slide swipe correctly, Please provide a non-working example

**Comment by nir9** [comment]
Closing due to no answer.
