### ISSUE TITLE
Unsupported jQuery code

### ISSUE THREAD

**Issue by vinceoralim** [nir9/itemslide#97]
Hi all,

JS lines 89 and 497 :
`carousel.currentLandPos = clamp( -(carousel.vars.allSlidesWidth - carousel.$el.parent().width()), 0, carousel.currentLandPos);`
raise the error : 
`carousel.$el.parent() is not a function`.
It seems they should be replaced by :
`carousel.currentLandPos = clamp( -(carousel.vars.allSlidesWidth - carousel.$el.parentElement.clientWidth), 0, carousel.currentLandPos);`

I didn't check if there are still other jQ oldies...

**Comment by nir9** [comment]
Thanks for reporting the bug :)
