### ISSUE TITLE
plugin breaks markup

### ISSUE THREAD

**Issue by vinceoralim** [nir9/itemslide#98]
Hi all,

My markup is : 
```
<ul>
  <li class="itemslide-li">...</li>
  <li class="itemslide-li">...</li>
  ...
</ul>
```

After initialisation (v2.0.0) :
`new Itemslide( elem , { disableClickToSlide:true , leftSided:true } );`

the markup is broke :
```
<ul>
  <li class=" itemslide-active">...</li>
  <li class="itemslide-li">...</li>
  ...
</ul>
```

The custom class has gone, note the space before `itemslide-active`.
Even after a manual fix, the custom class is also removed by the plugin, when the user scrolls the slide.

So, I'm staying on v1.6.0 which works flawlessly.

**Comment by nir9** [comment]
Thanks for reporting the bug, fixed in latest commit also published a new version (2.0.1) with the fix to NPM
